package com.demo.models;
// Generated Nov 23, 2022, 2:56:37 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lever generated by hbm2java
 */
@Entity
@Table(name = "lever", catalog = "project4")
public class Lever implements java.io.Serializable {

	private Integer leverId;
	private String name;
	private Set<Question> questions = new HashSet<Question>(0);

	public Lever() {
	}

	public Lever(String name) {
		this.name = name;
	}

	public Lever(String name, Set<Question> questions) {
		this.name = name;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lever_id", unique = true, nullable = false)
	public Integer getLeverId() {
		return this.leverId;
	}

	public void setLeverId(Integer leverId) {
		this.leverId = leverId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lever")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
